### ISSUE TITLE
Support for pandas data frame

### ISSUE THREAD

**Issue by cane11** [YosefLab/Hotspot#17]
Hi,
With the current master support for pandas data frame as input is disabled. I think it would be good to have old behavior as an option and not bind completely to anndata and especially layers for input. For destVI paper (https://github.com/romain-lopez/DestVI-reproducibility/blob/master/lymph_node/deconvolution/DestVI-LN.ipynb) e.g. we used hotspot on cell type proportions, which seems not supported anymore. Can you otherwise add a tag before the current release for better reproducibility?

```
loc = pd.DataFrame(data=st_adata.obsm["location"], index=st_adata.obs.index)
hs = hotspot.Hotspot(st_adata.obsm["proportions"].T, model='none', latent=loc,)
```

**Comment by adamgayoso** [comment]
There is a tag for the prior version:

https://github.com/YosefLab/Hotspot/tree/v0.9.1

Also, creating the input anndata takes just about as much code as what you have there

```
bdata = anndata.AnnData(st_adata.obsm["proportions"])
bdata.obsm["spatial"] = st_adata.obsm["location"]
hs = hotspot.Hotspot(bdata, model='none', latent_obsm_key="spatial")
```

**Comment by cane11** [comment]
Thank you, good suggestion to just make an anndata data file. I will go ahead with this solution.
