### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by flyingrobin** [YosefLab/Hotspot#2]
Very cool tool! I thoroughly enjoyed reading your paper, the tutorial, and your code. I work at 10x Genomics and I am interested in examining your methodology further and exploring potential applications to 10x data. I noticed that your code does not carry a license. Can you please add a license? 

Thank you.

**Comment by deto** [comment]
Didn't realize I hadn't added a license yet - thanks for pointing it out!

Added the MIT License
