### ISSUE TITLE
hs.plot_local_correlations() shows nothing

### ISSUE THREAD

**Issue by joyduck** [YosefLab/Hotspot#23]
I tried hotspot demo: Transcriptional Patterns in CD4 T Cells, but the hs.plot_local_correlations() function pops no plot, did not see any error messages, could you please let me know what are the possible reasons and resolutions for this? I'm currently running ubuntu 22.04, analysis was done with python 3.10. Thanks.

**Comment by adamgayoso** [comment]
I just double checked and it works for me in google colab. I would imagine this is a matplotlib issue. The code also hasn't been tested on python 3.10.

**Comment by joyduck** [comment]
closing this issue for now, plt.show() will resolve the problem
