### ISSUE TITLE
reproducibility of Hotspot analysis

### ISSUE THREAD

**Issue by joyduck** [YosefLab/Hotspot#28]
Hi there,
I have a question regarding the reproducibility of the hotspotsc analysis. I saved a Seurat analyzed dataset in h5ad format, pca and umap are all done and saved, and imported this object into python for the hs analysis. I started from adding count layer and log transformed layer, then went to construct a hs object and so on. but I noticed that the plotted correlation map varies very time I run it. tried to set random seed, but that did not seem help, just wondering what suggestions do you have to make the result more repeatable.
Thanks a lot.

**Comment by deto** [comment]
Hi Joyduck - the calculation should not be stochastic, so I'm unable to figure out where this discrepancy might be getting introduced.  We did change to enable an approximate nearest-neighbors construction that might have some inherent randomness.

Can you share how you are initializing/running the hotspot object? (the exact code).  Also, can you see if `obj.results` or `obj.local_correlation_z` are different (or is it just the appearance of the plot?)

**Comment by joyduck** [comment]
Thanks for your reply.
I tried to rerun my codes, but now the problem is gone, not sure what exactly happened, I guess we can close this issue for now.
