### ISSUE TITLE
All FDRs are NaNs

### ISSUE THREAD

**Issue by caitsimop** [YosefLab/Hotspot#40]
Hi! Thank you for your awesome tool!

I'm currently running into an issue where all my FDRs from the `compute_autocorrelation()` output are NaNs:

| C                   | Z                  | Pval | FDR | Gene  |
|---------------------|--------------------|------|-----|-------|
| 0.13755434709065900 | 232.93794207999100 | 0.0  | NaN | Gene1 |
| 0.03294967447345000 | 194.89686061627600 | 0.0  | NaN | Gene2 |
| 0.26574641897110900 | 190.262872995      | 0.0  | NaN | Gene3 |
| 0.38349791909887500 | 182.42394535670000 | 0.0  | NaN | Gene4 |
| 0.9111968018086300  | 178.3172181046050  | 0.0  | NaN | Gene5 |

Is this expected or is this an issue with my data? Thank you!

**Comment by caitsimop** [comment]
I believe this is due to inadequate data filtering on my end. I will close this for now!

**Comment by AtlasMaroc** [comment]
@caitsimop could you elaborate on the filtereing strategie you used ?
