### ISSUE TITLE
Save correlation plot

### ISSUE THREAD

**Issue by ccruizm** [YosefLab/Hotspot#7]
Good day!

I would like to know how I can export the plot generated by `plot_local_correlations`.   I tried `hs.plot_local_correlations(vmin=-30, vmax=30).savefig('plot.pdf')` but did not work. 

Thanks in advance!

**Comment by deto** [comment]
Ah, that function creates the plot with matplotlib, but doesn't actually return the figure.

So instead, to save it, run `plt.savefig('plot.pdf')` right after calling hs.plot_local_correlations  (you will have needed to have previously imported `matplotlib.pyplot` as `plt`)
